### ISSUE TITLE
Display hint map messages in grader output

### ISSUE THREAD

**Issue by sravanareddy** [sravanareddy/cs111grader#18]
Currently, the hint-map message gets added to the `Grades.messages` list, but we only display the 0th item. 

Change this so the message gets added to its own variable, not `messages` as a catch-all, and is appropriately displayed.

**Comment by dkreimer** [comment]
Right now the hint map messages seem to be targeted at specific error, do we want to keep that or have a general for all error or even all failures?

**Comment by sravanareddy** [comment]
We eventually want to have some backup general messages, yes. Let's get this working first. :)
