### ISSUE TITLE
Subsection for each function

### ISSUE THREAD

**Issue by sravanareddy** [sravanareddy/cs111grader#24]
(From student feedback)

Within each question, group together test cases of the same function under a single header or panel.

**Comment by sravanareddy** [comment]
Note: it may be cleaner to do this at the test case specification level rather than hacking it based on the function name. Let's have another level of nesting (test_cases/q1/functionname/1.test).

**Comment by dkreimer** [comment]
Would the subsections also be collapsible tabs or would they just be grouped by function name and possibly separated by a line or a header?

**Comment by sravanareddy** [comment]
Putting some touches on other parts, and can get started on this. Hold off.
