### ISSUE TITLE
Write script to allow easy input of test cases

### ISSUE THREAD

**Issue by sravanareddy** [sravanareddy/cs111grader#3]
Script should read from a single file, possibly with this format:

`functionName arg1 arg2 ... returnValue`

and create a set of `.test` and `.solution` files.

**Comment by sravanareddy** [comment]
Great job! I rearranged the files a bit. 

Could you also have the script generate a CONFIG file like the one in `test_cases/q2` that automatically generates the `max_points` based on the total number of test cases in the input file?

**Comment by dkreimer** [comment]
sure, thought since we have cases that I made manually, it wouldn't take those into account. Should I go ahead and just delete those files and create new ones from the script?

**Comment by sravanareddy** [comment]
No need to delete them.

Let's assume that every test case for a given question is created by the script (rather than some manually and some automatically), so the total number of test cases is the number of lines in the file.
