### ISSUE TITLE
Weighting of test cases

### ISSUE THREAD

**Issue by sravanareddy** [sravanareddy/cs111grader#5]
Use an existing class in `testClasses.py` or write a new one to allow for each test case to have a different weight.

**Comment by sravanareddy** [comment]
Any progress on this?

**Comment by dkreimer** [comment]
I'm having trouble testing it because python keeps pointing out indentation errors in the grading.py file - and the indentation in it is pretty weird. Every time I try to run it's either an indentation error or something I can assume comes from one.

**Comment by sravanareddy** [comment]
Oops -- the change I pushed with the Jinja introduced some weird indentations. Fixed now.

**Comment by sravanareddy** [comment]
Nice work! Can you display these weightings in the HTML output so it's clear how much each test case costs?

**Comment by dkreimer** [comment]
Alright, would something like:

<pre>
test_cases/q1/beats1.test
   beats('rock','scissors') returns True if gesture1 beats gesture2; False otherwise
   weight: 1
</pre>

be good in the test cases, or were you thinking something flashier outside of the messages area?

**Comment by sravanareddy** [comment]
That should be enough. Perhaps call it "score" instead of "weight"? Also, explicitly showing the earned score for each case might be good -- i.e.,

```
score: 1/1
```

for passed cases, and 

```
score: 0/1
```

for failed ones.

**Comment by dkreimer** [comment]
Does that mean that it should be possible to earn partial credits on tests? The way it works right now is if you fail you just get 0

**Comment by sravanareddy** [comment]
No, you just get all or nothing -- so yeah, the display is a bit redundant, but I think it's still helpful for students to see where the points have gone.
