### ISSUE TITLE
Basic HTML output

### ISSUE THREAD

**Issue by sravanareddy** [sravanareddy/cs111grader#6]
Create a simple HTML version of the current autograder's output. (Can add Javascript and CSS niceness later).

**Comment by dkreimer** [comment]
Would it be like a template for one case in the style of jinja or would it be using specific cases?

**Comment by sravanareddy** [comment]
A single template with HTML markup in place of ASCII (for now).

On Jun 10, 2016, at 4:45 PM, dkreimer notifications@github.com wrote:

Would it be like a template for one case in the style of jinja or would it
be using specific cases?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/sravanareddy/cs111grader/issues/6#issuecomment-225291120,
or mute the thread
https://github.com/notifications/unsubscribe/ABJ_iMkB39rZZmJVeZCit0DwQWyUCgpsks5qKcz3gaJpZM4IzRVi
.

**Comment by sravanareddy** [comment]
Any progress?

**Comment by dkreimer** [comment]
Yep, just put one up. Also realized that I forgot to commit the edits to the test case creator to show the specific test cases used in each one, but it's on my other computer so that will be up later.

**Comment by sravanareddy** [comment]
Looks good! Can you work on filling in the "holes' with the autograded output? I recommend using Jinja2 like the cs111 Web APIs.

**Comment by dkreimer** [comment]
so i discovered that if you run the autograder with --edx-output you actually get an html page

**Comment by sravanareddy** [comment]
Nice find! We should make it a bit fancier, though (like separating passes and fails, modularizing summary versus details, etc). The function to change seems to be `produceOutput` in `grading.py`. Take a stab at it without Jinja for the time being, though we'd like to use it eventually. 

I modified the code so that the HTML output is the default (no need for the  --edx-output).

Can we meet tomorrow at 3:30? Let's plan to work on it together for an hour or so. Before that, try to get as much of the output HTML done as you can.

**Comment by dkreimer** [comment]
sounds good!

**Comment by sravanareddy** [comment]
Took a stab at this: combined your `template.html` with the existing edx output, and added bootstrap styling.

Bootstrap is a popular CSS+Javascript package that has nice clean color schemes out of the box, and easy ways to do collapsible divs. See http://www.w3schools.com/bootstrap/ or one of the many other Bootstrap tutorials online.

For Friday, try to get the longform divs to collapse and uncollapse when the "question" buttons are clicked. Also feel free to play around with the styling and content if you like (this was a quick and dirty draft).

**Comment by sravanareddy** [comment]
Can you integrate the current template into `produceOutput` using jinja2? I've added a small jinja2 helper function. Essentially, create a new version of `template.html` with "holes" in it, and figure out how to pass the parameters.

**Comment by sravanareddy** [comment]
Checked in a start to this. See `jinjatemplate.html` and the changes to `grading.py`.

See the TODOs in `jinjatemplate.html`.
